#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above
# requirements (this script will be run on the server itself)
chmod 777 nginx
sudo apt -y update
sudo apt -y install nginx
echo "Hello World"
sudo service nginx restart
