#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
# header (on web-01 and web-02)
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "/listen 80 default_server;/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-enabled/default
sed -i "/listen 80 default_server;/a add_header X-Served-By: $hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
