#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
sudo apt-get -y update
sudo apt-get -y install nginx
#sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
#sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-enabled/default
#sudo service nginx restart
