#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt-get install -y haproxy
echo "listen 4372-lb-01" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4372-web-01 34.204.15.225:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4372-web-02 52.90.231.111:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart