#!/usr/bin/env bash
# This script does some stuff
touch /var/run/myscript.pid
while :
    do
      trap 'echo "I hate the kill command"' SIGTERM
			trap 'echo "Y U no love me?"' SIGINT
      echo "To infinity and beyond"
      sleep 2
    done
rm /var/run/myscript.pid
