#!/usr/bin/env bash
# This script does some stuff
touch /var/run/myscript.pid
while :
    do
      trap 'echo "I hate the kill command"' 'kill' SIGTERM
      trap 'rm -r /var/run/myscript.pid' 'kill' SIGTERM
      trap 'rm -r /var/run/myscript.pid' 'kill' SIGQUIT
			trap 'echo "Y U no love me?"' SIGINT
      echo "To infinity and beyond"
      sleep 2
    done
