#!/usr/bin/env bash
arr=("Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School")
for i in "${arr[@]}"; do echo "$i"; done
