#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "Hi" on 9
x=1
while [ $x -le 10 ]
do
  if [[ $x -eq 9 ]]
  then
    echo "Hi"
  else
    echo "Best School"
  fi
  x=$(( x + 1 ))
done
