#!/usr/bin/env bash
# This script prints "Best School" from 1 to 10 excepts on 4 and 8
x=1
while [ $x -le 10 ]
do
	if [[ $x -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $x -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$(( x + 1 ))
done
