#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
